version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: houndz
      POSTGRES_USER: houndz
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: gunicorn houndz.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  db_data:

